# Server config
server:
  port: 8081
  contextPath: /api/linfen
  display-name: sxops-linfen

logging:
  path: ../logs
  level:
    root: INFO
    com.sxops.www.dao.model: debug
    config: classpath:logback-spring.xml


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    # pool and driver class
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 1
    maxPoolPreparedStatementPerConnectionSize: -1
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  activemq:
    #    broker-url: 10.95.136.219:61616
    broker-url: tcp://10.97.100.218:61616
    user: meeting-reserve
    password: meeting-reserve123
  redis:
    host: 10.95.121.181
    port: 6379
    password: camelot123
    pool:
      maxActive: 1000
      maxWait: -1
      maxIdle: 200
      minIdle: 50
    timeout: 10000

mybatis:
  type-aliases-package: com.sxops.*.model
  mapper-locations: classpath:mapper/*.xml

# common mapper
mapper:
  mappers:
    - com.sxops.www.linfen.dao.util.MyBaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

third-api:
  #行政区划查询
  district-url: https://restapi.amap.com/v3/config/district?parameters
  district-key: 02f0d9cb6bcffc9698f6d11603138e7e
  district-method: GET




#上传附件格式配置\
file:
  suffix: doc,docx,xls,xlsx,ppt,pptx,zip,jpg,png,gif,jpeg,pdf
